let mazeModel = {
  size: 3,
  rows: [
    [
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
    ],
    [
      { isTall: true, isWide: false, isOpen: false },
      { isTall: true, isWide: true },
      { isTall: true, isWide: false, isOpen: false },
      { isTall: true, isWide: true },
      { isTall: true, isWide: false, isOpen: false },
      { isTall: true, isWide: true },
      { isTall: true, isWide: false, isOpen: false },
    ],
    [
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
    ],
    [
      { isTall: true, isWide: false, isOpen: false },
      { isTall: true, isWide: true },
      { isTall: true, isWide: false, isOpen: false },
      { isTall: true, isWide: true },
      { isTall: true, isWide: false, isOpen: false },
      { isTall: true, isWide: true },
      { isTall: true, isWide: false, isOpen: false },
    ],
    [
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
    ],
    [
      { isTall: true, isWide: false, isOpen: false },
      { isTall: true, isWide: true },
      { isTall: true, isWide: false, isOpen: false },
      { isTall: true, isWide: true },
      { isTall: true, isWide: false, isOpen: false },
      { isTall: true, isWide: true },
      { isTall: true, isWide: false, isOpen: false },
    ],
    [
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
      { isTall: false, isWide: true, isOpen: false },
      { isTall: false, isWide: false, isOpen: false },
    ],
  ],
};
